config/routes.rb
Rails.application.routes.draw do
  resources :mangas do
    member do
      post 'tag_create'
      delete 'tag_destroy'
    end
  end

  resources :tweets do
    collection do
      get 'user/:screen_name', to: 'tweets#user', as: 'user'
    end
  end

  resources :tags, :only => [:show]
  resources :authors, :only => [:index, :show]

  # You can have the root of your site routed with "root"
  root 'tweets#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/author.rb
class Author < ActiveRecord::Base
  extend FriendlyId
  friendly_id :screen_name, use: :slugged

  has_many :tweets
  paginates_per 50

  def normalize_friendly_id(string)
    string.gsub(/[\.\s]/, "-")
  end
end

app/models/manga.rb
class Manga < ActiveRecord::Base
  has_one :tweet
  has_many :manga_tags
  has_many :tags, :through => :manga_tags
end

app/models/manga_tag.rb
class MangaTag < ActiveRecord::Base
  belongs_to :manga
  belongs_to :tag
  validate :valid_relation_uniq

  # 既に登録済みのパターン(TagにもMangaTagsにも登録済み)
  def valid_relation_uniq
    if MangaTag.find_by(tag_id: tag_id, manga_id: manga_id)
      errors.add(:uniqs, '既に登録済みのタグを2重で登録しようとしています。')
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :manga_tags
  has_many :mangas, :through => :manga_tags

  validates :name, presence: true
  def normalize_friendly_id(string)
    string.gsub(/[\.\s]/, "-")
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :manga
  belongs_to :author
  paginates_per 50
  validates :tweet_id, presence: true, uniqueness: true

  def self.build_image(tweet)
    tweet_id  = tweet["tweet_id"].scan(/\/status\/(\d*)/).flatten.first
    return Hash.new if tweet_id.nil?

    client = twitter
    status = client.status(tweet_id.to_i)
    # 画像無しエラー
    # return tweet if status.media.empty?

    tweet["image_urls"] = status.media.map{|m| m.media_url.to_s}.join(',')
    backup = status.media.map do |m|
      imgur(m.media_url.to_s)
    end

    tweet["backup_image_urls"] = backup.map{|m| m[:link].to_s}.join(',')
    # http://imgur.com/delete/**
    tweet["backup_deletes"] = backup.map{|m| m[:deletehash].to_s}.join(',')

    tweet["uid"] = status.user.id
    tweet["user_name"] = status.user.name
    tweet["screen_name"] = status.user.screen_name
    tweet["tweet"] = status.text
    tweet["tweeted_at"] = status.created_at

    tweet
  end

  private

  def self.twitter
    Twitter::REST::Client.new do |config|
      config.consumer_key        = TWITTER_CONSUMER_KEY
      config.consumer_secret     = TWITTER_CONSUMER_SECRET
      config.access_token        = TWITTER_ACCESS_TOKEN
      config.access_token_secret = TWITTE_ACCESS_TOKEN_SECRET
    end
  end

  def self.imgur(imgurl)
    conn = Faraday.new
    config = {
      client_id: IMGUR_CLIENT_ID,
      client_secret: IMGUR_CLIENT_SECRET
    }
    res = conn.post 'https://api.imgur.com/3/image' do |request|
      request.headers = {Authorization: "Client-ID #{config[:client_id]}"}
      request.body = {image: imgurl}
    end
    result_hash = ActiveSupport::JSON.decode(res.body)
    return {
      link: result_hash["data"]["link"],
      deletehash: result_hash["data"]["deletehash"]
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.order("created_at DESC").page params[:page]
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweets = @author.tweets.order("created_at DESC").page params[:page]
  end
  private
    def set_author
      @author = Author.friendly.find(params[:id])
    rescue => e
      @error = '一度も登録されていないAuthorだお (´・ω・｀)'
    end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: [:tag_create, :tag, :tag_destroy]
  # GET /mangas
  # GET /mangas.json
  def index
    @mangas = Manga.all
  end

  def tag
  end

  # POST /mangas
  # POST /mangas.json
  def tag_create
    tag = Tag.find_by(name: tag_params["name"])
    respond_to do |format|
      begin
        @manga.tags.push tag.blank? ? Tag.new(tag_params) : tag
        if @manga.save
          format.json { render :tag, status: :created, location: @manga } 
        end
      rescue => e
        @error = e.to_s
        format.json { render json: @error, status: :unprocessable_entity } 
      end
    end
  end

  # DELETE /mangas/:id/tag_destroy
  def tag_destroy
    tag_id = Tag.friendly.find(params[:tag]).id
    MangaTag.where({
      tag_id: tag_id,
      manga_id: params[:id]}).destroy_all
    render :tag
  end

  private
    def set_manga
      @manga = Manga.find(params[:id])
    end

    def tag_params
      params.require(:manga).require(:tag).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.friendly.find(params[:id])
    rescue => e
      @error = '一度も登録されていないTag (´・ω・｀)'
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :destroy, :tag_create]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order("created_at DESC").page params[:page]
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  def user
    @tweets = Author.where(screen_name: params[:screen_name]).order("created_at DESC").page params[:page]
  end

  # POST /tweets
  # POST /tweets.json
  def create
    build_data = Tweet.build_image(tweet_params)
    @tweet = Tweet.new(build_data)
    @tweet.manga = Manga.new
    @tweet.author = Author.create_with(screen_name: @tweet.screen_name).find_or_create_by(twitter_uid: @tweet.uid)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet_id)
    end

    def tag_patams
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<div id="container">
  <% @tweets.each do |tweet| %>
    <%= render partial: 'shared/tweet_content', locals: { tweet: tweet, isform: false, first_only: false } %> 
  <% end %>
</div>

<%= paginate @tweets %>

<%= link_to '投稿する', new_tweet_path, :class => 'float-post' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookomi</title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <%= yield :header %>
</head>
<body>

<header><%= link_to 'Bookomi', root_path %></header>
<div id="wrapper" class="container">
  <%= yield %>
</div>

<%= yield :modal %>
<footer id="footer" class="mh_footer">
  <strong>© Boocomi, Inc.</strong>
</footer>

</body>
</html>

app/views/mangas/_form.html.erb
<%= form_for(@manga) do |f| %>
  <% if @manga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
      <% @manga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.text_field :tweet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mangas/edit.html.erb
<h1>Editing Manga</h1>

<%= render 'form' %>

<%= link_to 'Show', @manga %> |
<%= link_to 'Back', mangas_path %>

app/views/mangas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mangas</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mangas.each do |manga| %>
      <tr>
        <td><%= manga.tweet %></td>
        <td><%= link_to 'Show', manga %></td>
        <td><%= link_to 'Edit', edit_manga_path(manga) %></td>
        <td><%= link_to 'Destroy', manga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manga', new_manga_path %>

app/views/mangas/new.html.erb
<h1>New Manga</h1>

<%= render 'form' %>

<%= link_to 'Back', mangas_path %>

app/views/mangas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @manga.tweet %>
</p>

<%= link_to 'Edit', edit_manga_path(@manga) %> |
<%= link_to 'Back', mangas_path %>

app/views/mangas/tag.js.erb
$('#tag-block>.tag-list').html('<% @manga.tags.each do |tag| %><li><%=tag.name%></li><% end %>');

app/views/mangas/tag_error.js.erb
$('#notice').html('<%= @error %>');

app/views/shared/_embed.html.erb
<% content_for(:header) do %>
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<% end %>
<div class="tw-item">
  <blockquote class="twitter-tweet" <%="data-cards=hidden" unless tweet.image_urls.empty?%> lang="ja">
    <p><%= tweet.tweet %></p> &mdash; <%=tweet.user_name %> (@<%=tweet.screen_name%>)
    <a href="https://twitter.com/<%=tweet.screen_name%>/status/<%=tweet.tweet_id%>"><%=tweet.tweeted_at.strftime("%Y, %m月 %d")%></a>
  </blockquote>
</div>

app/views/shared/_tweet_content.html.erb
<div class="tw-container">
  <ul class="tw-info">
    <li class="post-date"><%= distance_of_time_in_words_to_now(tweet.tweeted_at) %>前</li>
  </ul>

  <%= render partial: 'tags/tag', locals: { tweet: tweet, isform: isform } %>
  <%= render partial: 'shared/tweet_img', locals: { tweet: tweet, first_only: first_only } %>

  <%= render partial: 'shared/embed', locals: { tweet: tweet } %>

  <div class="detail-link"><%= link_to ' 詳しく >>', tweet %></div>
  <ul class="tw-info">
    <li class="name"><%= tweet.user_name %></li>
    <li class="id">
      <%= link_to '@'+tweet.screen_name, author_path(tweet.author) rescue '@'+tweet.screen_name%>
    </li>
  </ul>
</div>

app/views/shared/_tweet_img.html.erb
<% tweet.image_urls.try(:split, ',').each_with_index do |image_url, i| %>
  <% break if(first_only && i != 0) %>
  <img class="tw-img" src="<%=image_url%>">
  <input class="tw-backup-img" value="<%= tweet.backup_image_urls.try(:split, ',').try(:[], i) %>" type="hidden">
<% end %>

app/views/tags/_tag.html.erb
<div class="tag-area">
  <table><tbody><tr>
    <td class="first-info">
      <div class="tip common-black">
        <% if defined? isform %>
          <a class="" href='#tag-modal' data-placement="left" data-toggle="modal" data-target="#tag-modal">
            <span>タグ<i class="glyphicon glyphicon-plus"></i></span>
          </a>
        <% else %>
          <span>タグ</span>
        <% end %>
      </div>
    </td>
    <td><div id="tag-block">
      <ul class="tag-list">
        <% tweet.manga.tags.each do |tag| %>
          <li><%= link_to tag.name, tag_path(tag) %></li>
        <% end %>
      </ul>
    </div></td>
  </tr></tbody></table>
</div>
<% if defined? isform %>
  <% content_for(:modal) do %>
    <%= render partial: 'tags/tag_form', locals: { manga: tweet.manga } %>
  <% end %>
<% end %>

app/views/tags/_tag_form.html.erb
<div class="modal fade" id="tag-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">タグ登録</h4>
      </div>
      <div class="modal-body">
        <ul id="modal-tag-lists">
          <% manga.tags.each do |tag| %>
            <li>
              <%= link_to tag_destroy_manga_path(manga, tag: tag), method: :delete, remote: true do %><i class="fa fa-trash-o"></i><% end %><span><%=tag.name%></span>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <%= form_for(manga, :url=> {
              controller: 'mangas',
              action: 'tag_create',
              id: manga.id
            }, :method => :post, :remote => true, format: :json) do |f| %>
          <div class="form-group col-xs-9">
            <%= f.fields_for manga.tags do |f_tag| %>
              <%= f_tag.text_field :name, value: '', class: 'form-control' %>
            <% end %>
          </div>
          <div class="form-submit col-xs-3">
            <%= f.submit "Add", class: 'btn btn-primary ' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<% if @error.present? %>
  <div id="error_explanation">
    <%= @error %>
  </div>
<% end %>
<section class="tag-caption">
  <div class="inner">
    <div id="content-header" class="result-word">
      <h1><%= @tag.try(:name) %></h1>

    </div>
  </div>
</section>
<div id="container">
  <% @tag.mangas.each do |manga| %>
    <%= render partial: 'shared/tweet_content', locals: { tweet: manga.tweet } %> 
  <% end %>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="tw-container">
  <div class="container">
    <div class="field form-group">
      <%= f.label :tweet_id, "URL" %><br>
      <%= f.text_field :tweet_id, :class => "form-control" %>
    </div>
  </div>
  <div class="actions">
      <%= f.submit :class => "btn btn-primary", :value => "投稿する" %>
  </div>
</div>

<% end %>


<div class="tw-container">
  使い方
  <br><br>
  ①面白い画像が投稿されているツイートの詳細を表示
  <br><br>
  <%= image_tag('how_to_use1.png') %>
  <br><br>
  ②URLをコピー
  <br><br>
  <%= image_tag('how_to_use2.png') %>
  <br><br>
  ③コピーしたURLを↓に貼り付け
  <br><br>
</div>

  <%= form_for(@tweet) do |f| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


  <div class="tw-container">
    <div class="container">
      <div class="field form-group">
        <%= f.label :tweet_id, "URL" %><br>
        <%= f.text_field :tweet_id, :class => "form-control" %>
      </div>
    </div>
    <div class="actions">
        <%= f.submit :class => "btn btn-primary", :value => "投稿する" %>
    </div>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<div id="container">
  <% @tweets.each do |tweet| %>
    <%= render partial: 'shared/tweet_content', locals: { tweet: tweet, isform: false, first_only: false } %>
  <% end %>
</div>

<%= paginate @tweets %>

<%= link_to '投稿する', new_tweet_path, :class => 'float-post' %>

app/views/tweets/new.html.erb
<div id="container">
  <%= render 'form' %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div id="container">
    <%= render partial: 'shared/tweet_content', locals: { tweet: @tweet, isform: true, first_only: false } %>
</div>

<%= link_to '投稿する', new_tweet_path, :class => 'float-post' %>

app/views/tweets/user.html.erb
<p id="notice"><%= notice %></p>

<div id="container">
  <% @tweets.each do |tweet| %>
    <%= render partial: 'shared/tweet_content', locals: { tweet: tweet, isform: false, first_only: false } %> 
  <% end %>
</div>

<%= paginate @tweets %>

<%= link_to '投稿する', new_tweet_path, :class => 'float-post' %>